### ISSUE TITLE
I need direction on how to use this please

### ISSUE THREAD

**Issue by rcc1622** [corkami/pocs#15]
I am using Pycharm.  I downloaded the entire package, and I have a project ready to go.  I also downloaded a png and dcm from Tiny.  I opened the console and typed "mitra.py pdf.pgn dicom.dcm" and it seemed to run, but I don't see the new polyglot anywhere so I'm not sure.  Your repository may be incredibly useful in polyglot detection experiments.  Please help, thank you.

**Comment by angea** [comment]
Tried `--verbose` for more info?
